class Config {

    static applicationId = 'com.chengshikezhan.chat'
    static appName = '城市客栈'
    static compileSdkVersion = 29
    static minSdkVersion = 21
    static targetSdkVersion = 29
    static versionCode = 147
    static versionName = '1.4.7.801'

    static kotlinVersion = '1.4.32'

    static depConfig = [
            /*Never delete this line*/
            /*Generated by "config.json"*/
            feature_launcher_app       : new DepConfig(true , true , ":feature:launcher:app"),
            feature_feature0_app       : new DepConfig(false, true , ":feature:feature0:app"),
            feature_feature0_pkg       : new DepConfig(true , true , ":feature:feature0:pkg"),
            feature_feature0_export    : new DepConfig(true , true , ":feature:feature0:export"),
            feature_mock               : new DepConfig(false, true , ":feature:mock"),
            lib_base                   : new DepConfig(true , true , ":lib:base"),
            lib_common                 : new DepConfig(true , true , ":lib:common"),
            lib_dbsample               : new DepConfig(false, true , ":lib:dbsample"),
            lib_imclient               : new DepConfig(true , true , ":lib:imclient", "com.watayouxiang:imclient:1.1.2"),
            lib_httpclient             : new DepConfig(true , true , ":lib:httpclient", "com.watayouxiang:httpclient:1.0.2"),
            lib_androidutils           : new DepConfig(true , true , ":lib:androidutils", "com.watayouxiang:androidutils:1.0.1"),
            lib_appupdate              : new DepConfig(true , true , ":lib:appupdate", "com.watayouxiang:appupdate:1.0.1"),
            lib_audiorecord            : new DepConfig(true , true , ":lib:audiorecord", "com.watayouxiang:audiorecord:1.0.1"),
            lib_db                     : new DepConfig(true , true , ":lib:db", "com.watayouxiang:db:1.0.1"),
            lib_qrcode                 : new DepConfig(true , true , ":lib:qrcode", "com.watayouxiang:qrcode:1.0.0"),
            lib_social_lib             : new DepConfig(true , true , ":lib:social-lib", "com.watayouxiang:social:1.0.0"),
            lib_social_tio             : new DepConfig(true , true , ":lib:social-tio", "com.tiocloud:social:1.0.0"),
            lib_webrtclib              : new DepConfig(true , true , ":lib:webrtclib", "com.watayouxiang:webrtclib:1.0.1"),
            lib_account                : new DepConfig(true , true , ":lib:account", "com.tiocloud:account:1.0.0"),
            lib_common_tio             : new DepConfig(true , true , ":lib:common-tio", "com.tiocloud:common:1.0.0"),
            lib_jpush                  : new DepConfig(true , true , ":lib:jpush", "com.tiocloud:jpush:1.0.0"),
            lib_session                : new DepConfig(true , true , ":lib:session", "com.tiocloud:session:1.0.0"),
            lib_verification           : new DepConfig(true , true , ":lib:verification", "com.tiocloud:verification:1.0.0"),
            lib_webrtc                 : new DepConfig(true , true , ":lib:webrtc", "com.tiocloud:webrtc:1.0.0"),
            lib_commonwallet           : new DepConfig(true , true , ":lib:commonwallet", "com.tiocloud:commonwallet:1.0.0"),
            lib_newpay                 : new DepConfig(true , true , ":lib:newpay", "com.tiocloud:newpay:1.0.0"),
            /*Never delete this line*/

            /*plugin start*/
            plugin_gradle                     : new DepConfig(pluginPath: "com.android.tools.build:gradle:4.2.1"),
            plugin_kotlin                     : new DepConfig(pluginPath: "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion", pluginId: "kotlin-android"),
            plugin_greendao                   : new DepConfig(pluginPath: "org.greenrobot:greendao-gradle-plugin:3.3.0", pluginId: "org.greenrobot.greendao"),
            plugin_agcp                       : new DepConfig(pluginPath: "com.huawei.agconnect:agcp:1.4.2.300", pluginId: "com.huawei.agconnect"),
            /*plugin end*/

            /*lib start*/
            junit                             : new DepConfig("junit:junit:4.13.2"),
            junit_ext                         : new DepConfig("androidx.test.ext:junit:1.1.2"),
            espresso_core                     : new DepConfig("androidx.test.espresso:espresso-core:3.3.0"),
            androidx_swiperefreshlayout       : new DepConfig("androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"),
            androidx_localbroadcastmanager    : new DepConfig("androidx.localbroadcastmanager:localbroadcastmanager:1.0.0"),
            androidx_cardview                 : new DepConfig("androidx.cardview:cardview:1.0.0"),
            androidx_annotation               : new DepConfig("androidx.annotation:annotation:1.1.0"),
            androidx_appcompat                : new DepConfig("androidx.appcompat:appcompat:1.2.0"),
            androidx_multidex                 : new DepConfig("androidx.multidex:multidex:2.0.0"),
            androidx_constraintlayout         : new DepConfig("androidx.constraintlayout:constraintlayout:2.0.4"),
            lifecycle_viewmodel_savedstate    : new DepConfig("androidx.lifecycle:lifecycle-viewmodel-savedstate:2.2.0"),
            kotlin                            : new DepConfig("org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"),
            material                          : new DepConfig("com.google.android.material:material:1.2.1"),

            payease_webox                     : new DepConfig("sdk.third-party.payease:webox:1.1.0"),
            payease_services                  : new DepConfig("sdk.third-party.payease:services:1.0.3"),
            heytap_msp_push                   : new DepConfig("sdk.third-party.jpush:com.heytap.msp-push:2.1.0"),
            liveness_silent_offline_cn_release: new DepConfig("sdk.third-party.payease:liveness-silent-offline-cn-release:1.10.0"),

            base_rvadapter                    : new DepConfig("com.zhy:base-rvadapter:3.0.2"),
            rxjava2_rxandroid                 : new DepConfig("io.reactivex.rxjava2:rxandroid:2.0.2"),
            reactive_streams                  : new DepConfig("org.reactivestreams:reactive-streams:1.0.2"),
            retrofit2                         : new DepConfig("com.squareup.retrofit2:retrofit:2.8.1"),
            retrofit2_converter_gson          : new DepConfig("com.squareup.retrofit2:converter-gson:2.8.1"),
            retrofit2_rxjava2_adapter         : new DepConfig("com.jakewharton.retrofit:retrofit2-rxjava2-adapter:1.0.0"),
            retrofit2_converter_scalars       : new DepConfig("com.squareup.retrofit2:converter-scalars:2.1.0"),
            logging_interceptor               : new DepConfig("com.squareup.okhttp3:logging-interceptor:4.7.1"),
            fastjson                          : new DepConfig("com.alibaba:fastjson:1.2.59"),
            permission_yanzhenjie             : new DepConfig("com.yanzhenjie:permission:2.0.0-rc1"),
            lifecycle_extensions              : new DepConfig("android.arch.lifecycle:extensions:1.1.1"),
            rxlifecycle_components            : new DepConfig("com.trello.rxlifecycle2:rxlifecycle-components:2.1.0"),

            utilcode                          : new DepConfig("com.blankj:utilcodex:1.30.5"),
            commons_lang3                     : new DepConfig("org.apache.commons:commons-lang3:3.11"),
            fresco                            : new DepConfig("com.facebook.fresco:fresco:2.3.0"),
            fresco_animated_gif               : new DepConfig("com.facebook.fresco:animated-gif:2.3.0"),
            fresco_soloader                   : new DepConfig("com.facebook.fresco:soloader:2.3.0"),
            BaseRecyclerViewAdapterHelper     : new DepConfig("com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.45-androidx"),
            Permission                        : new DepConfig("com.watayouxiang:Permission:2.0.1"),
            DemoShell                         : new DepConfig("com.watayouxiang:DemoShell:1.0.8"),
            widgetlibrary                     : new DepConfig("com.watayouxiang:widgetlibrary:0.0.4"),
            EasyPhotos                        : new DepConfig("com.github.HuanTanSheng:EasyPhotos:3.0.6"),
            glide                             : new DepConfig("com.github.bumptech.glide:glide:4.11.0"),
            glide_compiler                    : new DepConfig("com.github.bumptech.glide:compiler:4.11.0"),
            MNImageBrowser                    : new DepConfig("com.github.maning0303:MNImageBrowser:V1.2.5X"),
            leakcanary_android                : new DepConfig("com.squareup.leakcanary:leakcanary-android:2.6"),
            qmui                              : new DepConfig("com.qmuiteam:qmui:2.0.0-alpha10"),
            GSYVideoPlayer                    : new DepConfig("com.shuyu:GSYVideoPlayer:8.0.0"),
            greendao                          : new DepConfig("org.greenrobot:greendao:3.3.0"),
            GreenDaoUpgradeHelper             : new DepConfig("io.github.yuweiguocn:GreenDaoUpgradeHelper:v2.2.1"),
            okhttp3                           : new DepConfig("com.squareup.okhttp3:okhttp:4.7.1"),
            okgo                              : new DepConfig("com.lzy.net:okgo:3.0.4"),
            gson                              : new DepConfig("com.google.code.gson:gson:2.8.6"),
            eventbus                          : new DepConfig("org.greenrobot:eventbus:3.1.1"),
            bga_qrcode_zxing                  : new DepConfig("cn.bingoogolapple:bga-qrcode-zxing:1.3.7"),
            wechat_sdk_android_without_mta    : new DepConfig("com.tencent.mm.opensdk:wechat-sdk-android-without-mta:5.1.6"),
            sina_weibo_sdk_core               : new DepConfig("io.github.watayouxiang.3rd:openDefault:4.3.6"),
            google_webrtc                     : new DepConfig("org.webrtc:google-webrtc:1.0.30039"),
            huawei_hms_push                   : new DepConfig("com.huawei.hms:push:5.0.4.302"),
            Butterknife                       : new DepConfig("com.jakewharton:butterknife:10.1.0"),
            ButterknifeCompiler               : new DepConfig("com.jakewharton:butterknife-compiler:10.1.0"),

            /*lib end*/
    ]
}